/**
 * registry.ts — Tool registry and dynamic execution engine
 *
 * Manages all available tools (built-in and dynamically created) and
 * provides the execution layer for bash / python / javascript snippets
 * created at runtime by OpenCode or the `create_tool` built-in.
 *
 * Lifecycle:
 *   1. Constructor loads built-in tools and any persisted tool JSON files
 *      from the `dataDir/tools/` directory.
 *   2. New tools can be registered at runtime via:
 *      - `register(name, module)` — for built-in tools with a custom executor.
 *      - `registerDynamic(def)` — for tools generated by OpenCode (skips the
 *        test-run step, persists JSON to disk for next startup).
 *   3. Failed dynamic tools are cleaned up with `unregister(name)` which
 *      removes them from memory and deletes the JSON file.
 *
 * Dynamic tool execution (`executeDynamic`) runs the tool's code in a
 * subprocess (bash / python / node).  If `LOCALCLAW_SANDBOX_ENABLED` is
 * set, commands are wrapped in a Docker container with `--network none`.
 */

import fs from 'fs'
import path from 'path'
import { execSync, execFileSync } from 'child_process'
import type { ToolDefinition, ToolModule } from './types.js'
import { readFileTool } from './builtin/read-file.js'
import { writeFileTool } from './builtin/write-file.js'
import { runBashTool } from './builtin/run-bash.js'
import { opencodeTaskTool } from './builtin/opencode-task.js'
import { webFetchTool } from './builtin/web-fetch.js'
import { generateImageTool } from './builtin/generate-image.js'
import { sendEmailTool } from './builtin/send-email.js'
import { sendTelegramTool } from './builtin/send-telegram.js'
import { fetchNewsTool } from './builtin/fetch-news.js'
import { weatherTool } from './builtin/weather.js'
import { browserAutomationTool } from './builtin/browser-automation.js'
import { frenchTvGuideTool } from './builtin/french-tv-guide.js'
import { wrapCommand, isSandboxAvailable } from './sandbox.js'

export class ToolRegistry {
  private tools = new Map<string, ToolModule>()
  private toolsDir: string

  constructor(dataDir: string) {
    this.toolsDir = path.join(dataDir, 'tools')
    fs.mkdirSync(this.toolsDir, { recursive: true })
    this.registerBuiltins()
    this.loadPersisted()
  }

  // ---- Built-in tools ----

  private registerBuiltins() {
    for (const tool of [
      readFileTool,
      writeFileTool,
      runBashTool,
      webFetchTool,
      opencodeTaskTool,
      generateImageTool,
      sendEmailTool,
      sendTelegramTool,
      fetchNewsTool,
      weatherTool,
      browserAutomationTool,
      frenchTvGuideTool,
      this.createToolDefinition,
    ]) {
      this.tools.set(tool.definition.name, tool)
    }
  }

  /** Load persisted tool JSON files from disk (created in previous sessions). */
  private loadPersisted() {
    const dir = this.toolsDir
    if (!fs.existsSync(dir)) return
    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith('.json')) continue
      try {
        const def: ToolDefinition = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf-8'))
        if (this.tools.has(def.name)) continue
        this.tools.set(def.name, {
          definition: def,
          execute: (args) => this.executeDynamic(def, args),
        })
      } catch { /* skip invalid tool */ }
    }
  }

  // ---- Dynamic tool execution ----

  /**
   * Execute a dynamically created tool definition.
   *
   * Supports three languages:
   *   - bash:   runs via `/bin/bash -c`, with optional Docker sandbox
   *   - python: writes a temp .py file, runs `python3 <file>`, cleans up
   *   - javascript:  runs via `node -e "…"`, with optional Docker sandbox
   *
   * Template variables `{{args}}` in the source code are replaced with the
   * JSON-serialized arguments object before execution.
   */
  private async executeDynamic(def: ToolDefinition, args: Record<string, any>): Promise<string> {
    const raw = def.code || ''
    const escaped = JSON.stringify(args)
    const useSandbox = isSandboxAvailable()

    if (def.language === 'python') {
      const tmp = path.join(this.toolsDir, `_run_${Date.now()}.py`)
      try {
        const wrapper = raw.includes('{{args}}')
          ? raw.replace('{{args}}', escaped)
          : `${raw}\n\nimport json\n_args = json.loads("""${escaped.replace(/"/g, '\\"')}""")\nprint(main(_args))`
        fs.writeFileSync(tmp, wrapper)
        if (useSandbox) {
          const cmd = wrapCommand(`python3 /tmp/_run_${path.basename(tmp)}`, this.toolsDir)
          return execSync(cmd, { encoding: 'utf-8', timeout: 30000, shell: '/bin/bash' }).trim()
        }
        return execFileSync('python3', [tmp], { encoding: 'utf-8', timeout: 30000 }).trim()
      } finally {
        try { fs.unlinkSync(tmp) } catch {}
      }
    }

    if (def.language === 'bash') {
      const script = raw.replace(/\{\{args\}\}/g, escaped)
      const cmd = useSandbox ? wrapCommand(script) : script
      return execSync(cmd, { encoding: 'utf-8', timeout: 30000, shell: '/bin/bash' }).trim()
    }

    // JavaScript (default)
    const jsCode = raw.replace(/\{\{args\}\}/g, escaped)
    // Wrap in IIFE to avoid global scope conflicts (e.g. `const location`)
    const wrappedCode = `(function(){${jsCode}\n})()`
    if (useSandbox) {
      const cmd = wrapCommand(`node -e "${wrappedCode.replace(/"/g, '\\"').replace(/\n/g, ';')}"`)
      return execSync(cmd, { encoding: 'utf-8', timeout: 30000, shell: '/bin/bash' }).trim()
    }
    return execFileSync('node', ['-e', wrappedCode], { encoding: 'utf-8', timeout: 30000 }).trim()
  }

  // ---- create_tool built-in ----

  /** Built-in tool that lets the Ollama model register new tools on the fly. */
  private createToolDefinition: ToolModule = {
    definition: {
      name: 'create_tool',
      description: 'Create and register a new tool that can be used in future conversations. The tool code can use JavaScript, Python, or Bash. The tool receives arguments as a JSON object.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'Tool name (snake_case, no spaces)' },
          description: { type: 'string', description: 'What the tool does' },
          language: { type: 'string', description: 'Language: javascript, python, or bash', enum: ['javascript', 'python', 'bash'] },
          code: { type: 'string', description: 'The tool implementation. For python: define a main(args) function that returns a string. For javascript: expression that evaluates to a string. For bash: shell script.' },
          parameters: { type: 'string', description: 'JSON schema for parameters: {"propName":{"type":"string","description":"..."}}' },
          required_params: { type: 'string', description: 'JSON array of required parameter names: ["param1","param2"]' },
        },
        required: ['name', 'description', 'language', 'code'],
      },
    },
    execute: async (args) => {
      const { name, description, language, code, parameters, required_params } = args
      if (this.tools.has(name)) {
        return `Tool "${name}" already exists. Edit it or choose a different name.`
      }

      const def: ToolDefinition = {
        name,
        description,
        language: language as any,
        code: code as string,
        parameters: {
          type: 'object',
          properties: parameters ? JSON.parse(parameters as string) : {},
          required: required_params ? JSON.parse(required_params as string) : [],
        },
      }

      // Test-run the tool before registering it.
      try {
        const result = await this.executeDynamic(def, { test: true })
        console.log(`Tool "${name}" test run result: ${result.slice(0, 200)}`)
      } catch (err: any) {
        return `Tool "${name}" test run FAILED: ${err.message}. Fix the code and try again.`
      }

      fs.writeFileSync(path.join(this.toolsDir, `${name}.json`), JSON.stringify(def, null, 2))

      this.tools.set(name, {
        definition: def,
        execute: (a) => this.executeDynamic(def, a),
      })

      return `Tool "${name}" created and registered successfully! You can now use it by calling the function tool_${name} in your responses.`
    },
  }

  // ---- Public API ----

  /** Register a built-in or external tool module (comes with its own execute). */
  register(name: string, tool: ToolModule): void {
    this.tools.set(name, tool)
  }

  /**
   * Register a dynamic tool without test run. Saves the definition JSON to
   * disk so it is available on next startup.  Used by OpenCode-created tools
   * and pre-planned tools where the bash command is trusted as-is.
   */
  registerDynamic(def: ToolDefinition): void {
    fs.writeFileSync(path.join(this.toolsDir, `${def.name}.json`), JSON.stringify(def, null, 2))
    this.tools.set(def.name, {
      definition: def,
      execute: (args) => this.executeDynamic(def, args),
    })
  }

  /**
   * Unregister a tool and delete its definition file from disk.
   * Used to remove dynamic tools that returned no data (0 chars) so the
   * model doesn't keep calling a broken tool.
   */
  unregister(name: string): void {
    this.tools.delete(name)
    const filePath = path.join(this.toolsDir, `${name}.json`)
    try { fs.unlinkSync(filePath) } catch { /* ignore */ }
  }

  /** List all registered tool definitions. */
  list(): ToolDefinition[] {
    return Array.from(this.tools.values()).map((t) => t.definition)
  }

  /** Look up a tool module by name. */
  get(name: string): ToolModule | undefined {
    return this.tools.get(name)
  }

  getSystemPrompt(): string {
    return 'You are localclaw, an autonomous AI agent. Use the available tools to accomplish the user\'s requests.'
  }

  parseToolCall(_text: string): null {
    return null
  }
}